"""FastAPI app: vestlus (project) CRUD, file upload, and POST /recommend.

/recommend flow: the frontend sends the full intake form every time, scoped to
a vestluse_id.
- First call has empty 'clarifications' -> we run the hard-filter and return the
  surviving candidates plus deterministic clarifying questions. No Claude call,
  nothing persisted beyond the intake itself.
- Second call has 'clarifications' present (answers, or {} if the user skipped)
  -> we run the single Claude ranking call, using the vestlus's uploaded files as
  extra context, and save the result as that vestlus's one immutable
  recommendation snapshot. Any /recommend call once a snapshot exists is
  rejected (409) — a new vestluse_id is required for a new recommendation.

Every request passes through AuditMiddleware, which stamps a request_id, resolves
the caller's session, and writes one events row. Access control (backend/auth.py)
is off unless AUTH_ENABLED is set, so local development is unchanged.
"""

import logging
import math
import os
from contextlib import asynccontextmanager
import time
import uuid

from dotenv import load_dotenv

load_dotenv()  # must run before any backend imports so module-level env reads are correct

from fastapi import Depends, FastAPI, HTTPException, Request, Response, UploadFile
from fastapi.responses import FileResponse
from pydantic import BaseModel
from starlette.concurrency import run_in_threadpool

from backend import (audit, auth, chat, db, files, measures, rate_limit, refine,
                     search, sources)
from backend.rank import rank

logging.basicConfig(
    level=os.environ.get("LOG_LEVEL", "INFO").upper(),
    format="%(asctime)s %(levelname)s %(name)s %(message)s",
)
log = logging.getLogger("backend.main")

# /docs, /redoc, /openapi.json are FastAPI's built-in routes — they are not
# decorated with Depends(auth.require_tester) like the routes below, because
# they are generated by FastAPI itself before any of our routes exist. Left on,
# they hand any caller the full API schema for free. Off whenever the gate is
# on, since a public docs page has no purpose once the app is behind logins.
_docs_kwargs = {} if not auth.enabled() else {
    "docs_url": None, "redoc_url": None, "openapi_url": None,
}
@asynccontextmanager
async def lifespan(app: FastAPI):
    """Everything that touches the database or the network, run once on startup.

    Deliberately NOT at module scope. Importing this module has to stay a pure
    import: the test suite does `from backend.main import app` before its
    fixtures redirect db.DATA_DIR at a tmp_path, so anything writing at import
    time writes the real data/app.db instead. Under uvicorn the lifespan runs
    before the first request is served, so production is unchanged.
    """
    db.init_db()
    log.info("db ready at %s", db.DB_PATH)

    # Retrieval index over the measure catalogue. Derived from the CSVs, so a
    # rebuild costs nothing but startup time — and a failure here must not stop
    # the API: search.select_candidates() falls back to keeping every candidate.
    try:
        search.reindex_if_stale(MEASURES)
    except Exception as exc:  # pragma: no cover - startup resilience
        log.warning("chunk index unavailable, retrieval will keep all candidates: %s", exc)

    if not auth.enabled():
        log.warning("AUTH_ENABLED is not set — every endpoint is open to anyone who can reach it")

    # Optional source-scraping background job. Import is guarded so a missing or
    # broken scraper package can never stop the API from starting.
    try:
        from scraper.scheduler import start_background_scheduler

        start_background_scheduler()
    except Exception as exc:  # pragma: no cover - startup resilience
        log.warning("scraper scheduler unavailable: %s", exc)

    yield


app = FastAPI(title="AI Funding Advisor", lifespan=lifespan, **_docs_kwargs)

# Read-only: parses the CSVs into memory and touches no database, so it is safe
# at import time and the routes below can close over it.
MEASURES = measures.load_measures()
log.info("loaded %d measures", len(MEASURES))

FRONTEND = os.path.join(os.path.dirname(os.path.dirname(__file__)), "frontend", "index.html")


class AuditMiddleware:
    """Stamp every request with an id and identity, then record it in the audit trail.

    Written as raw ASGI rather than BaseHTTPMiddleware on purpose: Starlette runs
    BaseHTTPMiddleware's downstream app in a separate task, and context variables
    set before call_next do not reliably reach the route handler. Here everything
    happens in one task, so the request_id set below is the one llm.py sees when
    it writes an llm_calls row several frames deeper.
    """

    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope["type"] != "http":
            return await self.app(scope, receive, send)

        request = Request(scope, receive=receive)
        rid = uuid.uuid4().hex[:16]
        audit.request_id.set(rid)
        audit.vestluse_id.set(None)

        tester_id = auth.cookie_tester(request)
        audit.tester_id.set(tester_id)
        # rate_limit and the route dependencies read identity from here.
        scope.setdefault("state", {})["tester_id"] = tester_id

        started = time.monotonic()
        status_holder = {"code": 500}

        async def send_wrapper(message):
            if message["type"] == "http.response.start":
                status_holder["code"] = message["status"]
            await send(message)

        try:
            await self.app(scope, receive, send_wrapper)
        finally:
            state = scope.get("state") or {}
            # Off the event loop: log_event writes to SQLite, and doing that
            # inline would serialise every request behind a disk write.
            await run_in_threadpool(
                audit.log_event,
                ip=request.client.host if request.client else None,
                method=scope.get("method"),
                path=scope.get("path"),
                action=state.get("action"),
                vestlus=state.get("vestluse_id"),
                thread_id=state.get("thread_id"),
                status_code=status_holder["code"],
                duration_ms=int((time.monotonic() - started) * 1000),
                detail=state.get("detail"),
            )


app.add_middleware(AuditMiddleware)


def _mark(request: Request, *, action: str | None = None, vestluse_id: str | None = None,
          thread_id: str | None = None, detail: dict | None = None) -> None:
    """Attach context to this request's audit row.

    vestluse_id is written twice on purpose: to request.state for the middleware
    (which runs back on the event loop and cannot see this thread's context) and
    to the context variable for llm.py (which runs deeper in this same thread).
    """
    if action:
        request.state.action = action
    if vestluse_id:
        request.state.vestluse_id = vestluse_id
        audit.vestluse_id.set(vestluse_id)
    if thread_id:
        request.state.thread_id = thread_id
    if detail:
        request.state.detail = detail


def _owned_vestlus(request: Request, vestluse_id: str) -> dict:
    """Fetch a vestlus, 404 if missing and 403 if it belongs to another tester."""
    vestlus = db.get_vestlus(vestluse_id)
    if vestlus is None:
        raise HTTPException(status_code=404, detail="vestlust ei leitud")
    auth.require_owner(request, vestlus["tester_id"])
    return vestlus


def _readable_vestlus(request: Request, vestluse_id: str) -> dict:
    """Fetch a vestlus the caller is allowed to READ.

    The owner always may. Anyone else may only if the owner explicitly saved it:
    saving is what turns the code into something meant to be handed to a
    colleague. Unsaved work stays private, and every other verb — upload,
    recommend, delete, chat — still goes through _owned_vestlus, so a shared
    code grants reading and nothing more.
    """
    vestlus = db.get_vestlus(vestluse_id)
    if vestlus is None:
        raise HTTPException(status_code=404, detail="vestlust ei leitud")

    owner = vestlus["tester_id"]
    caller = getattr(request.state, "tester_id", None)
    if not auth.enabled() or owner is None or caller == owner:
        return vestlus
    if not vestlus["saved"]:
        raise HTTPException(status_code=403, detail="see vestlus ei kuulu sulle")

    _mark(request, detail={"shared_read": True, "owner": owner})
    return vestlus


def _owned_thread(request: Request, thread_id: str) -> dict:
    """Fetch a thread and verify the caller owns the vestlus it belongs to.

    Without this a known thread_id was enough to read or extend anyone's chat —
    the handlers used to look the thread up and never ask whose it was.
    """
    thread = db.get_thread(thread_id)
    if thread is None:
        raise HTTPException(status_code=404, detail="threadi ei leitud")
    _owned_vestlus(request, thread["vestluse_id"])
    return thread


class RecommendRequest(BaseModel):
    vestluse_id: str
    intake: dict
    # None = first call (return questions). A dict (even empty, if the user
    # skipped) = second call (run ranking). This is why we key off None, not
    # emptiness — an empty dict still means "the user is done answering".
    clarifications: dict | None = None


class SaveRequest(BaseModel):
    title: str


class RefineRequest(BaseModel):
    measure_names: list[str]
    willing_to_change: str = ""


class ThreadCreateRequest(BaseModel):
    measure_id: str


class MessageCreateRequest(BaseModel):
    content: str


class LoginRequest(BaseModel):
    code: str


def _recommendation(vestluse_id: str) -> dict | None:
    """Salvestatud soovitus, mille allikaseis on värskeim, mis meil on.

    Soovitus ise on lukustatud hetktõmmis, aga `source_status` mitte — vt
    sources.refresh_cards(). Kõik lugejad käivad siit läbi, et vestlusesse
    minev fookuskaart ja UI näitaksid sama seisu.
    """
    return sources.refresh_cards(db.get_recommendation(vestluse_id), MEASURES)


def _refinement(vestluse_id: str) -> dict | None:
    """Viimane täiendava analüüsi käik, sama värske allikaseisuga kui soovitus.

    refresh_cards() ootab võtit "ranked_cards"; täiendava analüüsi kaartidel on
    sama kuju, nii et anname talle lihtsalt selle nime all sama listi.
    """
    refinement = db.get_latest_refinement(vestluse_id)
    if refinement:
        sources.refresh_cards({"ranked_cards": refinement["cards"]}, MEASURES)
    return refinement


@app.get("/healthz")
def healthz():
    """Liveness probe for the container healthcheck. Never gated, never logged in."""
    return {"ok": True, "measures": len(MEASURES)}


@app.post("/login")
def login(req: LoginRequest, request: Request, response: Response):
    rate_limit.check_rate_limit(request)
    if not auth.enabled():
        return {"ok": True, "auth": "disabled"}
    tester = auth.login(req.code)
    if tester is None:
        _mark(request, action="login_failed")
        raise HTTPException(status_code=401, detail="tundmatu kood")
    auth.set_session_cookie(response, tester["tester_id"])
    _mark(request, action="login", detail={"tester": tester["name"]})
    return {"ok": True, "name": tester["name"]}


@app.post("/logout")
def logout(request: Request, response: Response):
    _mark(request, action="logout")
    auth.clear_session_cookie(response)
    return {"ok": True}


@app.get("/me")
def me(request: Request):
    """Who am I — lets the frontend decide whether to show the login overlay."""
    if not auth.enabled():
        return {"authenticated": True, "auth": "disabled"}
    tester_id = getattr(request.state, "tester_id", None)
    tester = db.get_tester(tester_id) if tester_id else None
    if tester is None or not tester["active"]:
        return {"authenticated": False}
    return {"authenticated": True, "name": tester["name"]}


@app.post("/vestlused")
def create_vestlus(request: Request, tester=Depends(auth.require_tester)):
    rate_limit.check_rate_limit(request)
    vestluse_id = db.create_vestlus(tester_id=tester)
    _mark(request, action="vestlus_create", vestluse_id=vestluse_id)
    return {"vestluse_id": vestluse_id}


@app.get("/vestlused")
def list_vestlused(request: Request, tester=Depends(auth.require_tester)):
    """The caller's own saved vestlused, so recovery does not depend on the code.

    Only saved ones: scratch sessions would otherwise fill the list with rows
    the tester never meant to keep.
    """
    rate_limit.check_rate_limit(request)
    _mark(request, action="vestlused_list")
    if tester is None:  # gate disabled -> no owner to scope by
        return {"vestlused": []}
    return {"vestlused": db.list_saved_vestlused(tester)}


@app.get("/vestlused/{vestluse_id}")
def get_vestlus(vestluse_id: str, request: Request, tester=Depends(auth.require_tester)):
    rate_limit.check_rate_limit(request)
    vestlus = _readable_vestlus(request, vestluse_id)
    _mark(request, action="vestlus_read", vestluse_id=vestluse_id)
    return {
        **vestlus,
        "owned": vestlus["tester_id"] is None or vestlus["tester_id"] == tester,
        "files": db.list_files(vestluse_id),
        "recommendation": _recommendation(vestluse_id),
        "refinement": _refinement(vestluse_id),
        "threads": db.list_threads(vestluse_id),
    }


@app.post("/vestlused/{vestluse_id}/save")
def save_vestlus(vestluse_id: str, req: SaveRequest, request: Request,
                 tester=Depends(auth.require_tester)):
    """Keep this vestlus: name it, list it, and make its code shareable."""
    rate_limit.check_rate_limit(request)
    _owned_vestlus(request, vestluse_id)
    title = req.title.strip()
    if not title:
        raise HTTPException(status_code=400, detail="anna vestlusele nimi")
    if len(title) > 120:
        title = title[:120]
    _mark(request, action="vestlus_save", vestluse_id=vestluse_id)
    if not db.save_vestlus(vestluse_id, title):
        raise HTTPException(status_code=404, detail="vestlust ei leitud")
    return {"vestluse_id": vestluse_id, "title": title, "saved": True}


@app.delete("/vestlused/{vestluse_id}")
def delete_vestlus(vestluse_id: str, request: Request, tester=Depends(auth.require_tester)):
    rate_limit.check_rate_limit(request)
    _owned_vestlus(request, vestluse_id)
    _mark(request, action="vestlus_delete", vestluse_id=vestluse_id)
    if not db.delete_vestlus(vestluse_id):
        raise HTTPException(status_code=404, detail="vestlust ei leitud")
    return {"ok": True}


# Deliberately sync `def`: save_upload() writes up to 10 MB and then parses
# PDF/DOCX/XLSX, all blocking. As `async def` that ran on the event loop and
# stalled every other user's request for the duration of one big upload.
@app.post("/vestlused/{vestluse_id}/files")
def upload_file(vestluse_id: str, request: Request, file: UploadFile,
                tester=Depends(auth.require_tester)):
    rate_limit.check_rate_limit(request)
    _owned_vestlus(request, vestluse_id)
    # Files are locked to the pre-recommendation context; no uploads after ranking.
    if db.has_recommendation(vestluse_id):
        raise HTTPException(status_code=409, detail="soovitus on lukustatud, loo uus vestlus")
    try:
        filename = files.safe_filename(file.filename or "")
    except ValueError:
        raise HTTPException(status_code=400, detail="lubamatu failinimi")
    if not files.is_allowed(filename):
        raise HTTPException(status_code=400, detail="lubamatu failitüüp")

    data = file.file.read()
    if len(data) > files.MAX_FILE_BYTES:
        raise HTTPException(status_code=413, detail="fail on liiga suur (max 10 MB)")

    _mark(request, action="file_upload", vestluse_id=vestluse_id,
          detail={"name": filename, "bytes": len(data)})
    return files.save_upload(vestluse_id, filename, data)


@app.delete("/vestlused/{vestluse_id}/files/{file_id}")
def delete_file(vestluse_id: str, file_id: int, request: Request,
                tester=Depends(auth.require_tester)):
    rate_limit.check_rate_limit(request)
    _owned_vestlus(request, vestluse_id)
    # Single-file deletion is only allowed before the recommendation is locked.
    if db.has_recommendation(vestluse_id):
        raise HTTPException(status_code=409, detail="soovitus on lukustatud")
    path = db.delete_file(vestluse_id, file_id)
    if path is None:
        raise HTTPException(status_code=404, detail="faili ei leitud")
    if os.path.exists(path):
        os.remove(path)
    _mark(request, action="file_delete", vestluse_id=vestluse_id, detail={"file_id": file_id})
    return {"ok": True}


@app.post("/recommend")
def recommend(req: RecommendRequest, request: Request, tester=Depends(auth.require_tester)):
    rate_limit.check_rate_limit(request)
    _owned_vestlus(request, req.vestluse_id)
    _mark(request, action="recommend", vestluse_id=req.vestluse_id)
    if db.has_recommendation(req.vestluse_id):
        raise HTTPException(status_code=409, detail="soovitus on juba olemas, loo uus vestlus")

    db.update_vestlus_intake(req.vestluse_id, intake=req.intake, clarifications=req.clarifications)

    candidates, dropped = measures.filter_candidates(MEASURES, req.intake)
    names = [c["name"] for c in candidates]

    # First call: no clarifications yet -> return questions, skip the LLM.
    if req.clarifications is None:
        questions = measures.get_clarifying_questions(candidates)
        _mark(request, action="recommend_questions",
              detail={"candidates": len(names), "dropped": len(dropped)})
        return {"candidates": names, "questions": questions, "dropped": dropped, "ranked_cards": []}

    # Second call: user answered or skipped. The hard filter kept everyone this
    # applicant is eligible for; retrieval now narrows that to what the project
    # is actually about, so the ranking call sees the relevant measures rather
    # than the whole catalogue. Measures cut here stay visible in 'dropped'.
    query = search.build_query(req.intake, req.clarifications)
    candidates, cut = search.select_candidates(candidates, query)
    dropped = dropped + cut
    names = [c["name"] for c in candidates]

    # ...then the single Claude ranking call, using this vestlus's uploaded files
    # as extra context, and lock the snapshot.
    rate_limit.check_llm_rate_limit(request)
    files_context = files.build_context_text(req.vestluse_id)
    try:
        cards = rank(candidates, req.intake, req.clarifications, files_context)
    except Exception as e:
        log.error("Claude ranking call failed for %s: %s", req.vestluse_id, e)
        raise HTTPException(status_code=502, detail="soovitust ei õnnestunud koostada, proovi uuesti")
    try:
        db.save_recommendation(req.vestluse_id, names, dropped, cards)
    except ValueError:  # lost a race with a concurrent /recommend call
        raise HTTPException(status_code=409, detail="soovitus on juba olemas, loo uus vestlus")
    _mark(request, action="recommend_ranked",
          detail={"cards": len(cards), "rag_kept": len(names), "rag_cut": len(cut)})
    return {"candidates": names, "questions": [], "dropped": dropped, "ranked_cards": cards}


@app.post("/vestlused/{vestluse_id}/refine")
def refine_measures(vestluse_id: str, req: RefineRequest, request: Request,
                    tester=Depends(auth.require_tester)):
    """Second pass: what would have to change for the user's picked measures to fit.

    Only measures that survived the hard filter are eligible. A measure that was
    dropped was dropped on a company fact the applicant cannot edit, so no amount
    of rewriting the application would bring it back — accepting one here would
    promise something we cannot deliver.

    Owner-only, like every other write. Reading a shared vestlus does not entitle
    you to spend its owner's LLM budget on it.
    """
    rate_limit.check_rate_limit(request)
    vestlus = _owned_vestlus(request, vestluse_id)
    _mark(request, action="refine", vestluse_id=vestluse_id)

    recommendation = _recommendation(vestluse_id)
    if recommendation is None:
        raise HTTPException(status_code=409, detail="soovitust pole veel tehtud")

    eligible = set(recommendation["candidates"])
    requested = list(dict.fromkeys(req.measure_names))  # de-dupe, keep order
    if not requested:
        raise HTTPException(status_code=400, detail="vali vähemalt üks meede")
    unknown = [n for n in requested if n not in eligible]
    if unknown:
        raise HTTPException(
            status_code=400,
            detail=f"need meetmed ei ole valitavad: {', '.join(unknown)}",
        )

    by_name = {m["name"]: m for m in MEASURES}
    selected = [by_name[n] for n in requested if n in by_name]
    if not selected:
        raise HTTPException(status_code=400, detail="valitud meetmeid ei leitud")

    batches = math.ceil(len(selected) / refine.BATCH_SIZE)
    rate_limit.check_llm_rate_limit(request, cost=batches)

    prior_cards = {c["name"]: c for c in recommendation["ranked_cards"]}
    files_context = files.build_context_text(vestluse_id)
    cards, failed = refine.refine(
        selected,
        vestlus["intake"],
        vestlus["clarifications"] or {},
        files_context,
        prior_cards,
        req.willing_to_change.strip(),
    )
    if not cards:
        raise HTTPException(
            status_code=502, detail="analüüsi ei õnnestunud koostada, proovi uuesti"
        )

    db.save_refinement(vestluse_id, requested, req.willing_to_change.strip(), cards, failed)
    _mark(request, action="refine_done",
          detail={"cards": len(cards), "failed": len(failed), "batches": batches})
    return {"cards": cards, "failed": failed}


@app.post("/vestlused/{vestluse_id}/threads")
def create_thread(vestluse_id: str, req: ThreadCreateRequest, request: Request,
                  tester=Depends(auth.require_tester)):
    rate_limit.check_rate_limit(request)
    _owned_vestlus(request, vestluse_id)

    recommendation = _recommendation(vestluse_id)
    if recommendation is None:
        raise HTTPException(status_code=409, detail="soovitust pole veel tehtud")
    focus_card = chat.find_focus_card(recommendation, req.measure_id)
    # A measure can reach the chat through the second pass without ever having
    # been a ranked card, so either source makes it a legitimate focus.
    refine_card = chat.find_refine_card(_refinement(vestluse_id), req.measure_id)
    if focus_card is None and refine_card is None:
        raise HTTPException(status_code=404, detail="meedet ei leitud soovituse seast")

    thread_id, created = db.get_or_create_thread(vestluse_id, req.measure_id)
    _mark(request, action="thread_create", vestluse_id=vestluse_id, thread_id=thread_id,
          detail={"measure_id": req.measure_id, "created": created})
    if created:
        seed = chat.seed_text(focus_card, refine_card)
        if seed:
            db.add_message(thread_id, "assistant", seed)
    return {"thread_id": thread_id, "measure_id": req.measure_id, "created": created}


@app.get("/threads/{thread_id}/messages")
def get_messages(thread_id: str, request: Request, tester=Depends(auth.require_tester)):
    rate_limit.check_rate_limit(request)
    thread = _owned_thread(request, thread_id)
    _mark(request, action="messages_read", vestluse_id=thread["vestluse_id"], thread_id=thread_id)
    return {
        "thread_id": thread_id,
        "vestluse_id": thread["vestluse_id"],
        "measure_id": thread["measure_id"],
        "messages": db.list_messages(thread_id),
    }


@app.post("/threads/{thread_id}/messages")
def post_message(thread_id: str, req: MessageCreateRequest, request: Request,
                 tester=Depends(auth.require_tester)):
    rate_limit.check_rate_limit(request)
    thread = _owned_thread(request, thread_id)
    _mark(request, action="message_send", vestluse_id=thread["vestluse_id"], thread_id=thread_id)
    if not req.content.strip():
        raise HTTPException(status_code=400, detail="sõnum on tühi")

    recommendation = _recommendation(thread["vestluse_id"])
    if recommendation is None:
        raise HTTPException(status_code=409, detail="soovitust pole veel tehtud")
    measure = measures.get_measure_by_id(MEASURES, thread["measure_id"])
    if measure is None:
        raise HTTPException(status_code=404, detail="meedet ei leitud")

    refine_card = chat.find_refine_card(
        _refinement(thread["vestluse_id"]), thread["measure_id"]
    )
    history = db.list_messages(thread_id, limit=chat.MAX_HISTORY_MESSAGES)
    # After "clear history" the thread is empty — re-seed the focus card's own
    # pitch before the new user message so the thread doesn't open blank.
    if not history:
        seed = chat.seed_text(
            chat.find_focus_card(recommendation, thread["measure_id"]), refine_card
        )
        if seed:
            db.add_message(thread_id, "assistant", seed)
            history = db.list_messages(thread_id, limit=chat.MAX_HISTORY_MESSAGES)

    # Before storing the user's turn: a 429 here must not leave a message in the
    # thread that never got a reply.
    rate_limit.check_llm_rate_limit(request)
    db.add_message(thread_id, "user", req.content)

    try:
        reply_text = chat.send_message(
            thread["vestluse_id"], measure, recommendation, history, req.content, refine_card
        )
    except Exception as e:
        log.error("Claude call failed for thread %s: %s", thread_id, e)
        raise HTTPException(status_code=502, detail="vastust ei saadud")

    db.add_message(thread_id, "assistant", reply_text)
    return {"thread_id": thread_id, "messages": db.list_messages(thread_id)}


@app.delete("/threads/{thread_id}/messages")
def clear_thread_messages(thread_id: str, request: Request, tester=Depends(auth.require_tester)):
    rate_limit.check_rate_limit(request)
    thread = _owned_thread(request, thread_id)
    _mark(request, action="messages_clear", vestluse_id=thread["vestluse_id"], thread_id=thread_id)
    db.clear_thread_messages(thread_id)
    return {"ok": True}


@app.get("/measures")
def list_measures(request: Request, tester=Depends(auth.require_tester)):
    rate_limit.check_rate_limit(request)
    return {
        "measures": [m["name"] for m in MEASURES],
        "measure_ids": {m["name"]: m["measure_id"] for m in MEASURES},
    }


@app.get("/")
def index():
    """The whole frontend, served with revalidation forced on every load.

    Without Cache-Control a browser applies *heuristic* freshness to a response
    that only carries Last-Modified/ETag, and happily reuses it without asking
    us — roughly 10% of the document's age, so a page that had been up for two
    days stayed cached for hours. That is not a cosmetic problem here: the app
    is one HTML file talking to an API it has to agree with, and after a deploy
    a stale page fails in confusing ways (clarifying questions became objects
    server-side and the old page rendered them as "[object Object]").

    'no-cache' does not mean "do not store" — the browser keeps the file and
    revalidates, so an unchanged page still costs one 304 and no download.
    """
    return FileResponse(FRONTEND, headers={"Cache-Control": "no-cache"})
